nodeLinker: node-modules

npmRegistryServer: "https://www.myget.org/F/ed-fi/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
