[tool.poetry]
name = "canvas-extractor"
version = "0.2.0"
description = ""
authors = ["Ed-Fi Alliance, LLC, and contributors"]
license = "Apache-2.0"
packages = [
    { include = "canvas_extractor" }
]

[tool.poetry.dependencies]
python = "^3.8"
jupyter = "^1.0.0"
pandas = "^1.1.2"
requests = "^2.24.0"
python-dotenv = "^0.14.0"
canvasapi = "^2.0.0"
xxhash = "^2.0.0"
SQLAlchemy = "^1.3.20"
opnieuw = "^1.1.0"
errorhandler = "^2.0.1"
ConfigArgParse = "^1.2.3"
edfi-lms-extractor-lib = {version = "1.0.0a1", allow-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
flake8 = "^3.8.4"
mypy = "^0.790"
pytest-describe = "^1.0.0"
coverage = "^5.3"
pook = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
