services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: lms_toolkit_mssql
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MSSQL_PORT}:1433
    volumes:
      - lms_toolkit_mssql-data:/var/opt/mssql

volumes:
  lms_toolkit_mssql-data:
     driver: local
     name: lms_toolkit_mssql-data
