[tool.poetry]
name = "lms-file-utils"
version = "0.1.0"
description = "Utilities to facilitate use of the filesystem created by Ed-Fi LMS Extractors"
authors = ["Ed-Fi Alliance, LLC and contributors"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.790"
pytest = "^6.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
