[tool.poetry]
name = "google-classroom-extractor"
version = "0.1.4"
description = ""
authors = ["Ed-Fi Alliance, LLC, and contributors"]
license = "Apache-2.0"
packages = [
    { include = "google_classroom_extractor" }
]

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^1.11.0"
google-auth-oauthlib = "^0.4.1"
pandas = "^1.1.1"
python-dotenv = "^0.14.0"
opnieuw = "^1.1.0"
tail-recursive = "^2.0.0"
SQLAlchemy = "^1.3.19"
teamcity-messages = "^1.28"
pytest = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pylint = "^2.6.0"
black = "^20.8b1"
flake8 = "^3.8.3"
faker = "^4.1.3"
coverage = "^5.3"
mypy = "^0.782"
pytest-describe = "^1.0.0"
pook = "^1.0.1"

[build-system]
requires = ["poetry>=1.0.10"]
build-backend = "poetry.masonry.api"
