name: Repository Security Scan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  action-allowedlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@main
        name: Scan GitHub Actions, and look for BIDI attacks
        id: scan-action
