name: Repository Security Scan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  dependency-scanning:
    name: Scan repo dependencies for security issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@main
        name: Scan GitHub Actions, and look for BIDI attacks
        id: scan-action

      - name: Dependency Review ("Dependabot on PR")
        uses: actions/dependency-review-action@0efb1d1d84fc9633afcdaad14c485cbbc90ef46c  # v2.5.1
