name: Repository Security Scan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  action-allowedlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2

      - uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/action-allowedlist@main
        name: Scan used actions
        id: scan-action
