name: Scan Actions
on:
  push:
    branches:
      - gh_actions_test
jobs:
  action-allowedlist:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/action-allowedlist@5d08097ea107de402454fbcbd2e276f8ce518a82
        name: Scan used actions
        id: scan-action  
