# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Canvas Extractor - Test
on:
  pull_request:
    paths:
      - "src/canvas-extractor/**"
      - "!src/canvas-extractor/**/*.md"
  push:
    paths:
      - "src/canvas-extractor/**"
      - "!src/canvas-extractor/**/*.md"
    branches:
      - main
  workflow_dispatch:

jobs:
  test-canvas-extractor:
    name: Run unit, style, and type checks
    runs-on: ubuntu-20.04
    env:
      PACKAGE_NAME: canvas-extractor
      SRC_DIR: src/canvas-extractor
      LOCK_FILE: src/canvas-extractor/poetry.lock
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.9
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v3.1.2
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Run CI Test Task
        run: |
          # Next line keeps poetry from trying to use the runner's default Python version
          pushd ${{ env.SRC_DIR }} && poetry env use "3.9" && popd
          python ./eng/build.py ci:test ${{ env.PACKAGE_NAME }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # "v3.1.0"
        with:
          name: code-coverage-report
          path: ${{ env.SRC_DIR }}/htmlcov/

      - name: Test Report
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        if: success() || failure() # run this step even if previous step failed
        with:
          name: PyTests # Name of the check run which will be created
          path: reports/reports-*.xml # Path to test results
          reporter: jest-junit # Format of test results
